import { z } from "zod";
import { RPC_CONTRACT, type RpcMethod } from "@chimera/protocol/contract";
import { QuestionAnswerSchema } from "@chimera/protocol";

export const OPERATOR_WEB_ALLOW = {
  "queue.list": "read", "queue.status": "read", "queue.statusSummary": "read", "review.get": "read", "evidence.get": "read",
  "queue.push": "control", "queue.cancelTask": "control", "queue.pause": "control", "queue.resume": "control",
  "review.finding.add": "control", "review.finding.resolve": "control", "review.decide": "control",
} satisfies Partial<Record<RpcMethod, "read" | "control">>;

// Legacy engine methods have not migrated to RPC_CONTRACT. Only this bounded
// projection is exposed; broad legacy params (identity, images, slash) stay local.
export const OPERATOR_WEB_LEGACY = {
  "project.list": { scope: "read", request: z.object({}).strict() },
  "agent.list": { scope: "read", request: z.object({}).strict() },
  "agent.status": { scope: "read", request: z.object({ agentId: z.string().min(1) }).strict() },
  "agent.tail": { scope: "read", request: z.object({ agentId: z.string().min(1), n: z.number().int().min(1).max(100).default(50) }).strict() },
  "agent.send": { scope: "control", request: z.object({ agentId: z.string().min(1), text: z.string().min(1).max(16000) }).strict() },
  "agent.hold": { scope: "control", request: z.object({ agentIds: z.array(z.string().min(1)).min(1).max(20) }).strict() },
  "agent.release": { scope: "control", request: z.object({ agentIds: z.array(z.string().min(1)).min(1).max(20) }).strict() },
  "agent.permissionRespond": { scope: "control", request: z.object({ requestId: z.string().min(1), allow: z.boolean() }).strict() },
  "agent.answerQuestion": { scope: "control", request: z.object({ questionId: z.string().min(1), answer: QuestionAnswerSchema }).strict() },
} as const;

export function webRequest(method: string, params: unknown) {
  if (Object.hasOwn(OPERATOR_WEB_LEGACY, method)) {
    const entry = OPERATOR_WEB_LEGACY[method as keyof typeof OPERATOR_WEB_LEGACY];
    return { scope: entry.scope, params: entry.request.parse(params) };
  }
  if (!Object.hasOwn(OPERATOR_WEB_ALLOW, method)) throw Object.assign(new Error("Method is unavailable in the operator panel"), { status: 403 });
  // Queue overrides can alter provider permissions and executable settings. The
  // panel submits text only into an existing, scoped queue.
  const schema = method === "review.get" ? z.object({ taskId: z.string().min(1) }).strict() : method === "queue.push" ? z.object({ queue: z.string().min(1), prompt: z.string().min(1).max(16000) }).strict()
    : RPC_CONTRACT[method as RpcMethod].request;
  const parsed = schema.parse(params) as Record<string, unknown>;
  if (Object.keys(parsed).some(k => /caller|principal|pushedBy|createdBy|actorAgentId|authorAgentId/i.test(k))) throw Object.assign(new Error("Caller identity is server-owned"), { status: 403 });
  return { scope: OPERATOR_WEB_ALLOW[method as keyof typeof OPERATOR_WEB_ALLOW], params: parsed };
}

// Explicit inventory: new contract methods must be classified during review.
export const OPERATOR_WEB_DENIED: Partial<Record<RpcMethod, string>> = {
  "canvas.get": "Local project graph; not authorized for browser sessions",
  "canvas.saveLayout": "Private operator layout; not authorized for browser sessions",
  "group.list": "Global Inspector registry; not scoped to browser projects",
  "group.create": "Global Inspector registry; not scoped to browser projects",
  "group.update": "Global Inspector registry; not scoped to browser projects",
  "group.delete": "Global Inspector registry; not scoped to browser projects",
  "agent.setGroups": "Inspector membership; not authorized for browser sessions",
  "agent.addGroups": "Inspector membership; not authorized for browser sessions",
  "agent.removeGroups": "Inspector membership; not authorized for browser sessions",
  "agent.forkCapabilities": "Local conversation capability; not authorized for browser sessions",
  "agent.fork": "Local conversation capability; not authorized for browser sessions",
  "contextlink.create": "Local capability; not authorized for browser sessions",
  "contextlink.list": "Local capability; not authorized for browser sessions",
  "contextlink.get": "Local capability; not authorized for browser sessions",
  "contextlink.revoke": "Local capability; not authorized for browser sessions",
  "worktree.gitStatus": "Local capability; not authorized for browser sessions",
  "worktree.gitDiff": "Local capability; not authorized for browser sessions",
  "worktree.fileRead": "Local capability; not authorized for browser sessions",
  "worktree.fileWrite": "Local capability; not authorized for browser sessions",
  "worktree.gitStage": "Local capability; not authorized for browser sessions",
  "worktree.gitCommit": "Local capability; not authorized for browser sessions",

  "operatorweb.operatorStatus": "Status is available through MCP; not a panel control",
  "operatorweb.status": "Local capability; not authorized for browser sessions",
  "operatorweb.enable": "Local capability; not authorized for browser sessions",
  "operatorweb.disable": "Local capability; not authorized for browser sessions",
  "operatorweb.pairStart": "Local capability; not authorized for browser sessions",
  "operatorweb.sessionList": "Local capability; not authorized for browser sessions",
  "operatorweb.sessionRevoke": "Local capability; not authorized for browser sessions",
  "operatorweb.settingsSet": "Local capability; not authorized for browser sessions",
  "issues.sourceList": "Local capability; not authorized for browser sessions",
  "issues.sourceUpsert": "Local capability; not authorized for browser sessions",
  "issues.sourceRemove": "Local capability; not authorized for browser sessions",
  "issues.sync": "Local capability; not authorized for browser sessions",
  "issues.linkList": "Local capability; not authorized for browser sessions",
  "issues.postComment": "Local capability; not authorized for browser sessions",
  "queue.create": "Local capability; not authorized for browser sessions",
  "queue.update": "Local capability; not authorized for browser sessions",
  "queue.delete": "Local capability; not authorized for browser sessions",
  "queue.requeue": "Local capability; not authorized for browser sessions",
  "queue.editTask": "Local capability; not authorized for browser sessions",
  "queue.moveTask": "Local capability; not authorized for browser sessions",
  "queue.retryTask": "Local capability; not authorized for browser sessions",
  "queue.addDependency": "Local capability; not authorized for browser sessions",
  "queue.explainTask": "Local capability; not authorized for browser sessions",
  "queue.requestRemediation": "Local capability; not authorized for browser sessions",
  "journal.query": "Local capability; not authorized for browser sessions",
  "history.runs": "Local capability; not authorized for browser sessions",
  "team.create": "Local capability; not authorized for browser sessions",
  "team.list": "Local capability; not authorized for browser sessions",
  "team.status": "Local capability; not authorized for browser sessions",
  "team.mine": "Local capability; not authorized for browser sessions",
  "team.dissolve": "Local capability; not authorized for browser sessions",
  "team.update": "Local capability; not authorized for browser sessions",
  "team.attachRole": "Local capability; not authorized for browser sessions",
  "team.detachRole": "Local capability; not authorized for browser sessions",
  "team.updateRoleBinding": "Local capability; not authorized for browser sessions",
  "role.create": "Local capability; not authorized for browser sessions",
  "role.list": "Local capability; not authorized for browser sessions",
  "role.update": "Local capability; not authorized for browser sessions",
  "role.delete": "Local capability; not authorized for browser sessions",
  "workflow.create": "Local capability; not authorized for browser sessions",
  "workflow.list": "Local capability; not authorized for browser sessions",
  "workflow.update": "Local capability; not authorized for browser sessions",
  "workflow.delete": "Local capability; not authorized for browser sessions",
  "workflow.run": "Local capability; not authorized for browser sessions",
  "workflow.plan": "Local capability; not authorized for browser sessions",
  "artifact.add": "Local capability; not authorized for browser sessions",
  "artifact.list": "Local capability; not authorized for browser sessions",
  "artifact.get": "Local capability; not authorized for browser sessions",
  "audit.verify": "Local capability; not authorized for browser sessions",
  "budget.resume": "Local capability; not authorized for browser sessions",
  "events.search": "Local capability; not authorized for browser sessions",
  "events.searchExport": "Local capability; not authorized for browser sessions",
  "chronicle.search": "Local capability; not authorized for browser sessions",
  "chronicle.get": "Local capability; not authorized for browser sessions",
  "chronicle.status": "Local capability; not authorized for browser sessions",
  "chronicle.reindex": "Local capability; not authorized for browser sessions",
  "skill.search": "Local capability; not authorized for browser sessions",
  "skill.read": "Local capability; not authorized for browser sessions",
  "terminal.append": "Local capability; not authorized for browser sessions",
  "terminal.read": "Local capability; not authorized for browser sessions",
  "terminal.write": "Local capability; not authorized for browser sessions",
  "terminal.tabState": "Local capability; not authorized for browser sessions",
  "agent.resources": "Local capability; not authorized for browser sessions",
  "host.admission": "Local capability; not authorized for browser sessions",
  "health.status": "Local capability; not authorized for browser sessions",
  "replay.agentsAsOf": "Local capability; not authorized for browser sessions",
  "shadow.workflowInspect": "Local capability; not authorized for browser sessions",
  "sub.create": "Local capability; not authorized for browser sessions",
  "sub.remove": "Local capability; not authorized for browser sessions",
  "sub.list": "Local capability; not authorized for browser sessions",
  "hook.list": "Local capability; not authorized for browser sessions",
  "hook.create": "Local capability; not authorized for browser sessions",
  "hook.update": "Local capability; not authorized for browser sessions",
  "hook.setEnabled": "Local capability; not authorized for browser sessions",
  "hook.delete": "Local capability; not authorized for browser sessions",
  "stt.configure": "Local capability; not authorized for browser sessions",
  "stt.status": "Local capability; not authorized for browser sessions",
  "stt.install": "Local capability; not authorized for browser sessions",
  "stt.installCancel": "Local capability; not authorized for browser sessions",
  "stt.uninstall": "Local capability; not authorized for browser sessions",
  "stt.transcribe": "Local capability; not authorized for browser sessions",
  "stt.transcribeCancel": "Local capability; not authorized for browser sessions",
  "voice.session.start": "Local capability; not authorized for browser sessions",
  "voice.session.stop": "Local capability; not authorized for browser sessions",
  "voice.conversation.set": "Local capability; not authorized for browser sessions",
  "voice.realtime.token": "Local capability; not authorized for browser sessions",
  "voice.native.check": "Local capability; not authorized for browser sessions",
  "voice.native.configure": "Local capability; not authorized for browser sessions",
  "voice.native.start": "Local capability; not authorized for browser sessions",
  "voice.native.poll": "Local capability; not authorized for browser sessions",
  "voice.native.stop": "Local capability; not authorized for browser sessions",
  "voice.native.history": "Local capability; not authorized for browser sessions",
  "voice.native.request": "Local capability; not authorized for browser sessions",
  "voice.native.requests": "Local capability; not authorized for browser sessions",
  "voice.native.dismiss": "Local capability; not authorized for browser sessions",
  "voice.native.end": "Local capability; not authorized for browser sessions",
  "voice.native.text": "Local capability; not authorized for browser sessions",
  "voice.room.create": "Local capability; not authorized for browser sessions",
  "voice.room.list": "Local capability; not authorized for browser sessions",
  "voice.room.update": "Local capability; not authorized for browser sessions",
  "voice.room.end": "Local capability; not authorized for browser sessions",
  "voice.room.delete": "Local capability; not authorized for browser sessions",
  "voice.room.approve": "Local capability; not authorized for browser sessions",
  "voice.room.reviewUpdate": "Local capability; not authorized for browser sessions",
  "voice.room.heartbeat": "Local capability; not authorized for browser sessions",
  "voice.room.cancelPlan": "Local capability; not authorized for browser sessions",
  "voice.room.plan": "Local capability; not authorized for browser sessions",
  "voice.room.report": "Local capability; not authorized for browser sessions",
  "voice.room.removeParticipant": "Local capability; not authorized for browser sessions",
  "mcpstore.oauth.start": "Local capability; not authorized for browser sessions",
  "mcpstore.oauth.finish": "Local capability; not authorized for browser sessions",
  "mcpstore.oauth.cancel": "Local capability; not authorized for browser sessions",
  "worktree.leaseList": "Local capability; not authorized for browser sessions",
  "worktree.leaseHandoff": "Local capability; not authorized for browser sessions",
  "worktree.leaseRelease": "Local capability; not authorized for browser sessions",
  "worktree.explainWrite": "Local capability; not authorized for browser sessions",
};
