// Homepage player regions and compatibility links share the capture manifest. The feature
// generator owns only its map/guide, so running either generator first cannot erase a player.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, join } from 'node:path';
const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const manifest = JSON.parse(readFileSync(join(root, 'site/assets/videos/provenance.json'), 'utf8'));
const escape = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const asset = f => `assets/videos/${escape(f)}`;
const clip = id => { const c=manifest.clips.find(c=>c.id===id); if(!c) throw new Error(`Missing homepage clip: ${id}`); return c; };
function player(id, theme='light') {
  const c=clip(id);
  // Each film keeps its own poster, including the illustrated overview.
  const poster=asset(c.files.poster);
  return `<figure class="demo-card demo-card--${theme}" id="${c.id}">
<video controls playsinline preload="none" width="${c.width??1280}" height="${c.height??800}" poster="${poster}" aria-label="${escape(c.title)}" aria-describedby="motion-note">
<source src="${asset(c.files.mp4.file)}" type="video/mp4">
<source src="${asset(c.files.webm.file)}" type="video/webm">
<track kind="captions" src="${asset(c.files.captions)}" srclang="en" label="English"${c.id==='product-overview'?'':' default'}>
Your browser cannot play this video. Read the text steps below.
</video>
<figcaption>${escape(c.title)} · ${c.durationSeconds.toFixed(1)}s</figcaption>
<p class="demo-links"><a href="${asset(c.files.steps)}">Text steps</a><a href="${poster}">Static poster</a><a href="${asset(c.files.captions)}">English captions</a></p>
</figure>`;
}
const topics=[['teams','team-worker-overview'],['projects','project-canvas'],['roles','role-library-binding'],['schedules','schedule-run-history'],['mcp-store','mcp-tool-inspection'],['secrets','secret-access-inspection'],['computer-use','desktop-preview']];
const features=JSON.parse(readFileSync(join(root,'site/features.json'),'utf8'));
const cards=topics.map(([topic,id])=>{
  const c=features.categories.find(c=>c.id===topic);
  return `<article class="gal__item">${player(id,'dark')}<h3>${escape(c.label)}</h3><p>${escape(c.short)}. <a class="link link--dark" href="features.html#${topic}">Read about ${escape(c.label.toLowerCase())}<span aria-hidden="true"> →</span></a></p></article>`;
}).join('\n');
const regions={
 hero:player('product-overview','hero'), queue:player('team-queue-lifecycle','dark'), memory:player('memory-search-link'),
 gallery:`<section class="sec sec--dark gal" id="demos" aria-labelledby="demos-title"><div class="wrap">
<span id="gallery" class="anchor-alias"></span>
<div class="head head--wide"><p class="kicker">In the app</p><h2 id="demos-title">See the rest of the workspace in motion.</h2>
<p class="sub">Inspect a team, trace a scheduled run, or follow the connections between tasks.</p>
<p id="motion-note" class="fine fine--dark">Playback starts when you choose it. These silent films include camera and pointer motion. Use captions, expand the player for small interface text, or read the text steps and static posters for reduced motion. <a href="how-made.html#videos">How these videos were made</a>.</p></div>
<div class="gal__grid"><article class="gal__item">${player('context-handoff','dark')}<h3>Context handoff</h3><p>Share an explicit snapshot with another session. <a class="link link--dark" href="features.html#memory">Read about shared memory<span aria-hidden="true"> →</span></a></p></article>
${cards}
<article class="gal__item">${player('resource-diagnostics','dark')}<h3>Agent resources</h3><p>Inspect the process tree and local resource readings. <a class="link link--dark" href="features.html#agents">Read about agents<span aria-hidden="true"> →</span></a></p></article>
</div></div></section>`
};
let home=readFileSync(join(root,'site/index.html'),'utf8');
for(const [name,body] of Object.entries(regions)) {
 const re=new RegExp(`<!-- videos:${name}:start[^>]*-->[\\s\\S]*?<!-- videos:${name}:end -->`);
 if(!re.test(home)) throw new Error(`Missing homepage region ${name}`);
 home=home.replace(re,`<!-- videos:${name}:start (generated by scripts/build-videos.mjs — do not edit) -->\n${body}\n<!-- videos:${name}:end -->`);
}
const heroPoster=asset(clip('product-overview').files.poster);
const preload=`<link rel="preload" as="image" href="${heroPoster}" fetchpriority="high" data-hero-poster>`;
home=home.replace(/\s*<link[^>]*data-hero-poster[^>]*>/,'').replace('<script src="script.js"',`${preload}\n  <script src="script.js"`);
const fallback=manifest.clips.map(c=>`<li id="${c.id}"><a href="index.html#${c.id}">${escape(c.title)}</a></li>`).join('\n');
const compatibility=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Chimera demos have moved to the homepage</title><meta name="description" content="Chimera product demos now play directly on the homepage, with English captions, native playback controls and text alternatives.">
<link rel="canonical" href="https://nedimyilmaz.github.io/chimera/"><meta property="og:image" content="https://nedimyilmaz.github.io/chimera/assets/og-image.png">
<link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script src="videos-redirect.js" defer></script>
</head><body><main class="sec"><div class="wrap"><h1>Demos now live on the homepage.</h1><p><a href="index.html#demos">Open the homepage demos</a>, or choose a film:</p><ul>${fallback}</ul><p><a href="how-made.html#videos">How these videos were made</a>.</p></div></main></body></html>\n`;
const tiles=manifest.clips.map(c=>`<td width="50%"><a href="https://nedimyilmaz.github.io/chimera/#${c.id}"><img src="site/assets/videos/${c.files.poster}" alt="${escape(c.title)} — play the demo" width="420"></a><br><strong>${escape(c.title)}</strong> · ${c.durationSeconds.toFixed(1)}s</td>`);
const posters=`<table>\n${tiles.map((t,i)=>i%2===0?`<tr>${t}${tiles[i+1]??''}</tr>`:'').filter(Boolean).join('\n')}\n</table>`;
const readme=readFileSync(join(root,'README.md'),'utf8').replace(/<!-- videos:readme:start -->[\s\S]*?<!-- videos:readme:end -->/,`<!-- videos:readme:start -->\n${posters}\n<!-- videos:readme:end -->`);
const outputs={'site/index.html':home,'site/videos.html':compatibility,'README.md':readme};
let stale=false;
for(const [path,content] of Object.entries(outputs)) {
 if(process.argv.includes('--check')) { if(readFileSync(join(root,path),'utf8')!==content){console.error(`${path} is stale`);stale=true;} }
 else writeFileSync(join(root,path),content);
}
if(stale) process.exitCode=1;
